add_newline = false
scan_timeout = 10
format = """\
[#](cyan) \
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$time\
$status
$character"""

[line_break]
disabled = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"

[cmake]
symbol = "▲ "

[directory]
truncate_to_repo = false
use_logical_path = true

[directory.substitutions]
'/' = '\'

[hostname]
ssh_only = false
format = "[$hostname](cyan) in "

[username]
user = "batkiz"
disabled = false

# show_always = true
[git_branch]
symbol = "git:"
format = "on [$symbol$branch](green) "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
ahead = "↑"
behind = "↓"
deleted = "×"

[time]
disabled = false
format = '[\[$time\]]() '
